# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: false
    labels:
      - "!autorelease: tagged" # release-please
  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: false
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
    biome:
      enabled: false
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    eslint:
      enabled: false
    actionlint:
      enabled: true
chat:
  auto_reply: true
knowledge_base:
  learnings:
    scope: local
  web_search:
    enabled: true
